In [1]:
import xarray as xr
import sys
import glob
import numpy as nmp

In [2]:
fresults=sorted(glob.glob('results/result_??.nc'))
ds=xr.open_mfdataset(fresults,concat_dim='time',combine='nested')

In [3]:
ds

<xarray.Dataset>
Dimensions:         (time: 10021)
Coordinates:
  * time            (time) float64 1.392e+18 1.392e+18 ... 1.397e+18 1.397e+18
Data variables:
    latitude        (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    longitude       (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    sossheig_np     (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    sossheig_bl     (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    sla_unfiltered  (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    distance        (time) float64 dask.array<chunksize=(148,), meta=np.ndarray>
    time_counter    (time) datetime64[ns] dask.array<chunksize=(148,), meta=np.ndarray>
Attributes:
    about:    Created with Gonzag package => https://github.com/brodeau/gonzag

In [4]:
ds.time_counter

<xarray.DataArray 'time_counter' (time: 10021)>
dask.array<concatenate, shape=(10021,), dtype=datetime64[ns], chunksize=(173,), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) float64 1.392e+18 1.392e+18 ... 1.397e+18 1.397e+18
Attributes:
    axis:           T
    long_name:      Time of measurement
    standard_name:  time

In [5]:
VT = ds.time

In [6]:
print(VT)

<xarray.DataArray 'time' (time: 10021)>
array([1.391683e+18, 1.391683e+18, 1.391683e+18, ..., 1.396827e+18,
       1.396827e+18, 1.396827e+18])
Coordinates:
  * time     (time) float64 1.392e+18 1.392e+18 ... 1.397e+18 1.397e+18
Attributes:
    axis:           T
    long_name:      Time of measurement
    standard_name:  time


In [7]:
VM=ds.sla_unfiltered

In [23]:
VM[3600:3700].values

array([ 0.102,  0.118,  0.12 ,  0.101,  0.121,  0.121,  0.102,  0.101,
        0.095,  0.075,  0.069,  0.062,  0.026,  0.059,  0.054,  0.051,
        0.064,  0.043,  0.057,  0.043,  0.042,  0.058,  0.07 ,  0.08 ,
        0.094,  0.089,  0.098,  0.106,  0.11 ,  0.111,  0.116,  0.102,
        0.096,  0.088,  0.091,  0.08 ,  0.045,  0.075,  0.043,  0.034,
        0.026,  0.047,  0.048,  0.046,  0.06 ,  0.066,  0.082,  0.111,
        0.117,  0.151,  0.161,  0.145,  0.259,  0.161,  0.115,  0.11 ,
        0.056,  0.05 ,  0.105,  0.07 ,  0.079,  0.031,  0.017,    nan,
          nan, -0.05 , -0.026,  0.008,  0.048,  0.093,  0.112,  0.119,
        0.113,  0.095,  0.088,  0.091,  0.076,  0.091,  0.114,  0.138,
        0.138,  0.118,  0.141,  0.124,  0.111,  0.136,  0.142,  0.131,
        0.13 ,  0.124,  0.138,  0.16 ,  0.168,  0.186,  0.158,  0.151,
        0.15 ,  0.137,  0.117,  0.124])

In [24]:
ii=nmp.where(nmp.isnan(VM.values)==1)

In [25]:
print(ii[0])

[3663 3664 8795 8796]


In [11]:
from gonzag.spectralysis import *


In [12]:
ISeg_beg, ISeg_end = FindUnbrokenSegments( ds.time, ds.distance, ds.sossheig_bl, \
                                             rcut_time=1.2e+09, rcut_dist=7.8 )


In [13]:
print(ISeg_beg, ISeg_end)

[    0    35    49   148   197   316   321   370   400   449   512   560
   611   648   697   719   768   885   934   964  1053  1056  1105  1224
  1229  1278  1397  1401  1450  1569  1574  1623  1650  1699  1802  1848
  1851  1970  1971  1997  2001  2050  2169  2174  2223  2342  2346  2356
  2395  2484  2495  2544  2663  2668  2707  2717  2745  2794  2857  2905
  2990  3035  3039  3052  3084  3101  3214  3263  3285  3292  3293  3302
  3376  3414  3425  3521  3542  3591  3710  3714  3763  3882  3887  3936
  3965  3989  3999  4014  4098  4125  4147  4266  4269  4311  4360  4479
  4484  4533  4652  4656  4676  4705  4807  4817  4856  4953  4975  5000
  5008  5024  5048  5097  5098  5158  5206  5238  5292  5341  5363  5408
  5412  5575  5618  5694  5696  5745  5766  5780  5860  5909  5982  6007
  6010  6056  6059  6085  6108  6169  6173  6222  6341  6345  6394  6435
  6513  6515  6552  6564  6583  6665  6714  6751  6800  6817  6866  6912
  6961  6966  6967  7004  7067  7116  7235  7239  7

In [14]:
print(len(ISeg_beg))

240


In [15]:
ds.distance[12].values-ds.distance[11].values

6.593076418648025

In [16]:
NbSeg, Nsl, IDEDSeg = SegmentSelection(ISeg_beg, ISeg_end, np_valid_seg=70)


 *** [SegmentSelection()]: Will use 24 segments with a fixed length of 100 points!
     ==> 24 selected segments out of the 240 available (requested minimum length is 70 points)



In [17]:
IDseg=IDEDSeg
Vd=ds.distance
VS=ds.sossheig_bl
VM=ds.sla_unfiltered

In [18]:
    from scipy.signal import detrend, tukey
    #
    #
    NbS = IDseg.shape[0] ; # number of segments
    if ivrb>1: print(' *** [Process4FFT()] NbS = ', NbS)

    Nsl = IDseg[0,1]-IDseg[0,0]+1 ; # length of segments
    if ivrb>1: print(' *** [Process4FFT()] Nsl = ', Nsl)
    
    vs_s = nmp.zeros((NbS,Nsl))
    vs_m = nmp.zeros((NbS,Nsl))
    


In [19]:
NbS

24

In [20]:
js=11

In [21]:
        it1 = IDseg[js,0]
        it2 = IDseg[js,1]


In [22]:
print(it1,it2)

3600 3699


In [ ]:
            dmean = nmp.mean(Vd[it1+1:it2+1].values-Vd[it1:it2].values)
            print(' *** [Process4FFT()]: Mean distance between two consecutive points is '+str(dmean)+' km\n')
            # Sample spacing in [km] (inverse of the sampling rate):
            dx_sample = nmp.round(dmean,3)
            print('     => will use a spatial sample spacing of '+str(dx_sample)+' km\n')


In [ ]:
Vd[it1+1:it2+1].values


In [ ]:
VS[it1:it2+1].values


In [ ]:
dmean = nmp.mean(Vd[it1+1:it2+1].values-Vd[it1:it2].values)

In [ ]:
print(dmean)

In [ ]:
dx_sample = nmp.round(dmean,3)

In [ ]:
dx_sample

In [ ]:
        vs_s[js,:] = VS[it1:it2+1].values
        vs_m[js,:] = VM[it1:it2+1].values


In [ ]:
            vs_s[js,:] = detrend(vs_s[js,:],type='linear')
            vs_m[js,:] = detrend(vs_m[js,:],type='linear')


In [ ]:
        vs_s[js,:] = vs_s[js,:] - nmp.mean(vs_s[js,:])
        vs_m[js,:] = vs_m[js,:] - nmp.mean(vs_m[js,:])


In [ ]:
            wdw =  tukey(Nsl,0.5)
            if js==0: print(' *** [Process4FFT()]: applying "Tukey" tappering...')
            vs_s[js,:] = vs_s[js,:]*wdw
            vs_m[js,:] = vs_m[js,:]*wdw


In [ ]:
XPs, XPm, rdist_sample = Process4FFT( IDEDSeg, ds.distance, ds.sossheig_bl, ds.sla_unfiltered )


In [ ]:
Kwn, PwSpc_s, PwSpc_m = ApplyFFT( IDEDSeg, XPs, XPm, rdist_sample )
