# GONZAG cloud example

In [1]:
import sys
from os import getenv
import warnings
warnings.filterwarnings("ignore")

In [2]:
from gonzag.config import *
from gonzag.io import *
from gonzag.utils import *
from gonzag.mod2sat import *
from gonzag.bilin_mapping import *
from gonzag.spectralysis import *


## Data

In [3]:
import xarray as xr
osn_url = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/swot_adac/eNATL60_surface_region_1'
dsmod = xr.open_zarr(osn_url, consolidated=True)

In [4]:
dsmod

<xarray.Dataset>
Dimensions:        (time_counter: 2136, x: 611, y: 763)
Coordinates:
    depth          (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1f            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1t            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1u            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e1v            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e2f            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e2t            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e2u            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    e2v            (y, x) float64 dask.array<chunksize=(763, 611), meta=np.ndarray>
    lat            (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    lon            (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    nav_lat        (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    nav_lon        (y, x) float32 dask.array<chunksize=(763, 611), meta=np.ndarray>
    time_centered  (time_counter) datetime64[ns] dask.array<chunksize=(72,), meta=np.ndarray>
  * time_counter   (time_counter) datetime64[ns] 2010-02-01T00:30:00 ... 2010...
Dimensions without coordinates: x, y
Data variables:
    fmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    qt_oce         (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    somecrty       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sometauy       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sosaline       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sossheig       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sosstsst       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sowaflup       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sozocrtx       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    sozotaux       (time_counter, y, x) float32 dask.array<chunksize=(72, 763, 611), meta=np.ndarray>
    tmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    umask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>
    vmask          (y, x) int8 dask.array<chunksize=(763, 611), meta=np.ndarray>

In [5]:
name_ssh_mod = 'sossheig'
name_lsm_mod = 'tmask' 
l_griddist = False

In [6]:
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/altimetry.yaml")
dssat  = cat["al"].to_dask()

In [7]:
dssat

<xarray.Dataset>
Dimensions:         (time: 34340107)
Coordinates:
    latitude        (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    longitude       (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
  * time            (time) datetime64[ns] 2013-03-14T05:44:50.445185024 ... 2...
Data variables:
    cycle           (time) int16 dask.array<chunksize=(34340107,), meta=np.ndarray>
    dac             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    lwe             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    mdt             (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    ocean_tide      (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    sla_filtered    (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    sla_unfiltered  (time) float64 dask.array<chunksize=(34340107,), meta=np.ndarray>
    track           (time) int16 dask.array<chunksize=(34340107,), meta=np.ndarray>
Attributes:
    Conventions:               CF-1.6
    Metadata_Conventions:      Unidata Dataset Discovery v1.0
    cdm_data_type:             Swath
    comment:                   Sea surface height measured by altimeters refe...
    contact:                   servicedesk.cmems@mercator-ocean.eu
    creator_email:             servicedesk.cmems@mercator-ocean.eu
    creator_name:              CMEMS - Sea Level Thematic Assembly Center
    creator_url:               http://marine.copernicus.eu
    history:                   2019-02-20T19:39:52Z: Creation
    institution:               CLS, CNES
    keywords:                  Oceans > Ocean Topography > Sea Surface Height
    keywords_vocabulary:       NetCDF COARDS Climate and Forecast Standard Names
    license:                   http://marine.copernicus.eu/web/27-service-com...
    platform:                  Altika
    processing_level:          L3
    product_version:           2019
    project:                   COPERNICUS MARINE ENVIRONMENT MONITORING SERVI...
    references:                http://marine.copernicus.eu
    software_version:          6.2_DUACS_DT2018_baseline
    source:                    Altika measurements
    ssalto_duacs_comment:      The reference mission used for the altimeter i...
    standard_name_vocabulary:  NetCDF Climate and Forecast (CF) Metadata Conv...
    summary:                   SSALTO/DUACS Delayed-Time Level-3 sea surface ...
    title:                     DT Altika Global Ocean Along track SSALTO/DUAC...

In [8]:
name_ssh_sat='sla_unfiltered'

## Time overlap between model and satellite ?
Assume that model is less than 1 year, satellite has at least one whole year, we take the overlapping period without considering which year is this

In [9]:
    (date1,date2), (Nts,Ntm) = GetTimeOverlap( dssat , dsmod )
    print(' *** Time overlap between model and satellite in UNIX epoch time: it1, it2',date1,'--',date2)


 *** [GetTimeInfo()] Getting calendar/time info in dataset ...
   => time/record dimension is "time"
   => first and last date:  2013-03-14T05:44:50.445185024 -- 2015-03-31T22:41:36.909480960
 *** [GetTimeInfo()] Getting calendar/time info in dataset ...
   => time/record dimension is "time_counter"
   => first and last date:  2010-02-01T00:30:00.000000000 -- 2010-04-30T23:30:00.000000000

 *** Earliest/latest dates:
   => for satellite data: 2013-03-14T05:44:50.445185024 2015-03-31T22:41:36.909480960 
   => for model     data: 2010-02-01T00:30:00.000000000 2010-04-30T23:30:00.000000000 

 *** Time overlap between model and satellite in UNIX epoch time: it1, it2 2014-02-01 -- 2014-04-30


## Create object `ModelGrid` containing all the model (aka _source_) 2D+T domain grid info

In [10]:
  
    ModelGrid = ModGrid( dsmod, date1 , date2 , dsmod, name_lsm_mod, distorded_grid=False )


 *** [GetModelCoor()] Read model latitude (variable is "lat", with 2 dimensions! (763, 611) 

 *** [GetModelCoor()] Read model longitude (variable is "lon", with 2 dimensions! (763, 611) 


 *** what we use to define model land-sea mask:
    => "tmask" in dataset 

 *** [GridResolution()] Based on the longitude array, the model resolution ~=  0.016657295  degrees 

 *** Skipping computation of angle distortion of the model grid! ("-D" option not invoked)...

 *** About model gridded (source) domain:
     * shape =  (763, 611)
     * horizontal resolution:  0.016657295  degrees or  1.8507920147292316  km
     * Is this a global domain w.r.t longitude:  False
       ==> this is a regional domain
       ==> working in the [0:360] frame...
     * lon_min, lon_max =  281.99 292.17
     * lat_min, lat_max =  30.01 40.01
     * should we pay attention to possible STRONG local distorsion in the grid:  False
     * number of time records of interest for the interpolation to come:  2136
       =

In [11]:
SatelliteTrack = SatTrack( dssat, date1, date2, Np=Nts, \
                              domain_bounds=ModelGrid.domain_bounds, l_0_360=ModelGrid.l360 )

 *** [SatTrack()] Analyzing the time vector in dataset ...
 *** [GetSatCoor()] reading "latitude" in dataset ...
   => 4150072 records read...

 *** [GetSatCoor()] reading "longitude" in dataset ...
   => 4150072 records read...


 *** About satellite track (target) domain:
     * number of time records of interest for the interpolation to come:  10236
       ==> time record indices: 14883510 to 19033581, included



In [12]:
MG= ModelGrid
ST= SatelliteTrack

In [13]:
print(ST.size*24/3600)

68.24


In [47]:
%%time

from gonzag.io   import GetModel2DVar, GetSatSSH
(Nj,Ni) = MG.shape

d_found_km = rfactor*MG.HResDeg*deg2km
print(' *** "found" distance criterion when searching for nearest point on model grid is ', d_found_km, ' km\n')

# Size of the search zoom box:
np_box_radius = SearchBoxSize( MG.HResDeg*deg2km, search_box_w_km )
print(' *** Will use zoom boxes of width of '+str(2*np_box_radius+1)+' points for 1st attempts of nearest-point location...\n')

Nt = ST.size ; # number of satellit observation point to work with here...

if_talk = Nt//nb_talk

Yt=ST.lat
Xt=ST.lon
Ys=MG.lat
Xs=MG.lon
src_grid_local_angle=MG.xangle
k_ew_per=MG.EWPer
rd_found_km=d_found_km
np_box_r=np_box_radius
freq_talk=if_talk

sangle = src_grid_local_angle
kewp   = k_ew_per
rfound = rd_found_km
nprad  = np_box_r
(Nj,Ni) = Ys.shape
        
NP = nmp.zeros((Nt,2)  , dtype=nmp.int64) ; # nearest point
SM = nmp.zeros((Nt,4,2), dtype=nmp.int64) ; # source mesh
WB = nmp.zeros((Nt,4))                    ; # weights

ftalk = 2*Nt ; # => will never talk!
if freq_talk>0: ftalk = int(freq_talk) ; # will talk every "ftalk" increments....
        
print('\n *** Finding nearest points on source (model) grid... (rd_found_km, np_box_r =',rd_found_km, np_box_r,')')

from gonzag.bilin_mapping import NearestPoint
#Nearest Point
xnp = nmp.zeros((Nt,2), dtype=nmp.int64)
#
[jj,ji] = [nprad,nprad] ; # stupid first guess here...

jt=10 # test with one timestep

print('      +++ Treated point: '+str(jt+1)+'/'+str(Nt), \
                      '\n          ==> Sat. coordinates:    ', nmp.round(Yt[jt],3), nmp.round(Xt[jt],3))
            
[jj,ji] = NearestPoint( (Yt[jt].values,Xt[jt].values), Ys.values, Xs.values, \
                                    rd_found_km=rfound, j_prv=jj, i_prv=ji, np_box_r=nprad )
print(jj,ji)
# Exclude points at first and last column if no E-W periodicity:
if ji==0 or ji==Ni-1 and kewp == -1: [jj,ji] = [-1,-1]
# Exclude points at first and last row:
if jj==0 or jj==Nj-1:                [jj,ji] = [-1,-1]
            
xnp[jt,:] = [jj,ji]

print('          ==> Model nearest point: ', \
                    nmp.round(Ys[jj,ji].values,3),nmp.round(Xs[jj,ji].values%360.,3),' (',jj,ji,')')

NP = xnp
print('     ***    Done! *** \n')

print('  *** Determining source meshes...')

from gonzag.bilin_mapping import IDSourceMesh

xsp = nmp.zeros((Nt,4,2), dtype=nmp.int64)

[jP,iP] = NP[jt,:]
if [jP,iP] != [-1,-1]:
    angle = 0.
    if nmp.shape(sangle) == nmp.shape(Ys): angle = sangle[jP,iP]
        #
    xsp[jt,:,:] = IDSourceMesh( (Yt[jt].values,Xt[jt].values), Ys.values, Xs.values, jP, iP, \
                                            k_ew_per=kewp, grid_s_angle=angle )
SM = xsp

print('     ***    Done! *** \n')
        
print('  *** Computing bilinear weights...')

from gonzag.bilin_mapping import WeightBL

x4w = nmp.zeros((Nt,4))
#
x4w[jt,:] = WeightBL( (Yt[jt].values,Xt[jt].values), Ys.values, Xs.values, SM[jt,:,:] )
#
WB = x4w

from gonzag.utils import PlotMesh

PlotMesh( (ST.lon[jt],ST.lat[jt]), MG.lat, MG.lon, SM[jt,:,:], WB[jt,:], \
                                  fig_name='mesh_jt'+'%5.5i'%(jt)+'.png' )

 *** "found" distance criterion when searching for nearest point on model grid is  1.3880940110469238  km

 *** Will use zoom boxes of width of 271 points for 1st attempts of nearest-point location...


 *** Finding nearest points on source (model) grid... (rd_found_km, np_box_r = 1.3880940110469238 135 )
      +++ Treated point: 11/10236 
          ==> Sat. coordinates:     <xarray.Variable ()>
array(39.398) <xarray.Variable ()>
array(289.495)
716 458
          ==> Model nearest point:  39.402 289.502  ( 716 458 )
     ***    Done! *** 

  *** Determining source meshes...
     ***    Done! *** 

  *** Computing bilinear weights...
CPU times: user 8.48 s, sys: 3.14 s, total: 11.6 s
Wall time: 14 s


In [40]:
print(Ni,Nj)

611 763


In [41]:
print(NP[0])

[-1 -1]


In [42]:
print(WB[0])

[0.25 0.25 0.25 0.25]


In [43]:
print(SM[0])

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [44]:
print(NP[0])

[-1 -1]


In [45]:
print(nprad)

135


In [46]:
print(Yt[jt].values,Xt[jt].values)

39.973308 289.681787


In [20]:
print(Ys.values, Xs.values)

[[30.010681 30.010723 30.010763 ... 30.037752 30.037798 30.037844]
 [30.024738 30.02478  30.024822 ... 30.051926 30.051973 30.05202 ]
 [30.038794 30.038836 30.038877 ... 30.066097 30.066145 30.06619 ]
 ...
 [39.76764  39.76797  39.768303 ... 39.98261  39.982975 39.98334 ]
 [39.779232 39.779564 39.779896 ... 39.994583 39.994953 39.99532 ]
 [39.79082  39.791157 39.79149  ... 40.006557 40.006924 40.007294]] [[282.00876 282.02542 282.04208 ... 292.14117 292.15784 292.1745 ]
 [282.00873 282.0254  282.04205 ... 292.1411  292.15778 292.17444]
 [282.00867 282.02533 282.042   ... 292.14105 292.15775 292.1744 ]
 ...
 [281.86728 281.88388 281.9005  ... 291.98077 291.99744 292.0141 ]
 [281.86688 281.88348 281.90012 ... 291.98032 291.99698 292.01364]
 [281.8665  281.88312 281.89972 ... 291.97986 291.99652 292.01318]]


In [21]:
(Ny,Nx) = Ys.shape

In [22]:
j_prv=nprad
i_prv=nprad
j1=max(j_prv-np_box_r,0) ; j2=min(j_prv+np_box_r+1,Ny)
i1=max(i_prv-np_box_r,0) ; i2=min(i_prv+np_box_r+1,Nx)


In [23]:
print(i1,j1,i2,j2)

0 0 271 271


In [24]:
from gonzag.utils import Haversine

In [25]:
xd = Haversine( Yt[jt],Xt[jt] ,  Ys[j1:j2,i1:i2], Xs[j1:j2,i1:i2] )

In [26]:
print(xd.values)

[[1306.35802752 1305.55113717 1304.74565532 ... 1142.20429722
  1141.8161505  1141.42987645]
 [1305.0099106  1304.20231423 1303.39594669 ... 1140.6849402
  1140.29613461 1139.90940835]
 [1303.66392499 1302.85560264 1302.04854246 ... 1139.16661698
  1138.77735289 1138.39017   ]
 ...
 [ 977.83339372  976.79371628  975.75516728 ...  753.41458744
   752.84170918  752.27130007]
 [ 976.75322984  975.7122445   974.67271216 ...  752.04525103
   751.47102734  750.89967212]
 [ 975.67405296  974.63210722  973.59156846 ...  750.67592104
   750.1011374   749.5288332 ]]


In [27]:
jy, jx = find_j_i_min( xd.values )

In [28]:
print(jy,jx)

270 270


In [29]:
xd[jy,jx].values

array(749.5288332)

In [30]:
print(rfound)

1.3880940110469238


In [31]:
lfound = ( xd[jy,jx].values < rfound )

In [32]:
print(lfound)

False


In [33]:
print(9*10236/3600)

25.59
